### ISSUE TITLE
Veiculo

### ISSUE THREAD

**Issue by developermarcos** [Chicado-Nulls/Locacao-De-Veiculos#14]
![Image](https://user-images.githubusercontent.com/82339940/176705564-6d464be8-4487-4cd3-a668-34a83de523bf.png)

Tela

- [x] Listar Todos

- [x] Listar

- [x] Inserir 

- [x] Editar

- [x] Excluir

Service

- [x] Listar Todos

- [x] Listar

- [x] Inserir 

- [x] Editar

- [x] Excluir

- [x] Validador campos

Repositorio

- [x] ListarTodos

- [x] ListarPorId

- [x] Inserir 

- [x] Editar

- [x] Excluir

- [x] Validar registro único

Domínio

- [x] Objeto

- [x] Validador

Repositorio Test

- [x] ListarTodos

- [x] ListarPorId

- [x] Inserir 

- [x] Editar

- [x] Excluir

Domínio Test

- [x] Objeto

- [x] Validador

**Comment by JoaoM0raes** [comment]
Refatorando e testando mue códgio para a feature de foto
